### ISSUE TITLE
Interrupt handler looks static but is a class method

### ISSUE THREAD

**Issue by cansik** [maechler/iot-home#1]
It seems that the interrupt handler should be a static method, because the first argument is called `timer`. But it in reality it is the instance of the class. Is this intended or should it look like this:

```python
def interrupt_handler(self, timer):
    CoreApp.interrupt_counter = 1 + CoreApp.interrupt_counter
```

**Comment by maechler** [comment]
Thanks, it is probably just lacking the `@staticmethod ` annotation, I will add it.
